# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1463/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1463/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/manuel/taller/Counter2D-2025c1-grupo9

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/manuel/taller/Counter2D-2025c1-grupo9

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/snap/cmake/1463/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1463/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/manuel/taller/Counter2D-2025c1-grupo9/CMakeFiles /home/manuel/taller/Counter2D-2025c1-grupo9//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/manuel/taller/Counter2D-2025c1-grupo9/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named taller_common

# Build rule for target.
taller_common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_common
.PHONY : taller_common

# fast build rule for target.
taller_common/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/build
.PHONY : taller_common/fast

#=============================================================================
# Target rules for targets named taller_client

# Build rule for target.
taller_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_client
.PHONY : taller_client

# fast build rule for target.
taller_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/build
.PHONY : taller_client/fast

#=============================================================================
# Target rules for targets named taller_server

# Build rule for target.
taller_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_server
.PHONY : taller_server

# fast build rule for target.
taller_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/build
.PHONY : taller_server/fast

#=============================================================================
# Target rules for targets named taller_editor

# Build rule for target.
taller_editor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_editor
.PHONY : taller_editor

# fast build rule for target.
taller_editor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_editor.dir/build.make CMakeFiles/taller_editor.dir/build
.PHONY : taller_editor/fast

#=============================================================================
# Target rules for targets named sdl_headers_copy

# Build rule for target.
sdl_headers_copy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sdl_headers_copy
.PHONY : sdl_headers_copy

# fast build rule for target.
sdl_headers_copy/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/sdl_headers_copy.dir/build.make _deps/sdl2-build/CMakeFiles/sdl_headers_copy.dir/build
.PHONY : sdl_headers_copy/fast

#=============================================================================
# Target rules for targets named SDL2main

# Build rule for target.
SDL2main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2main
.PHONY : SDL2main

# fast build rule for target.
SDL2main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2main.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2main.dir/build
.PHONY : SDL2main/fast

#=============================================================================
# Target rules for targets named SDL2

# Build rule for target.
SDL2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2
.PHONY : SDL2

# fast build rule for target.
SDL2/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2.dir/build
.PHONY : SDL2/fast

#=============================================================================
# Target rules for targets named SDL2-static

# Build rule for target.
SDL2-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2-static
.PHONY : SDL2-static

# fast build rule for target.
SDL2-static/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2-static.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2-static.dir/build
.PHONY : SDL2-static/fast

#=============================================================================
# Target rules for targets named SDL2_test

# Build rule for target.
SDL2_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_test
.PHONY : SDL2_test

# fast build rule for target.
SDL2_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2_test.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2_test.dir/build
.PHONY : SDL2_test/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/uninstall.dir/build.make _deps/sdl2-build/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named SDL2_image

# Build rule for target.
SDL2_image: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_image
.PHONY : SDL2_image

# fast build rule for target.
SDL2_image/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2_image-build/CMakeFiles/SDL2_image.dir/build.make _deps/sdl2_image-build/CMakeFiles/SDL2_image.dir/build
.PHONY : SDL2_image/fast

#=============================================================================
# Target rules for targets named SDL2_mixer

# Build rule for target.
SDL2_mixer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_mixer
.PHONY : SDL2_mixer

# fast build rule for target.
SDL2_mixer/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2_mixer-build/CMakeFiles/SDL2_mixer.dir/build.make _deps/sdl2_mixer-build/CMakeFiles/SDL2_mixer.dir/build
.PHONY : SDL2_mixer/fast

#=============================================================================
# Target rules for targets named SDL2_ttf

# Build rule for target.
SDL2_ttf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_ttf
.PHONY : SDL2_ttf

# fast build rule for target.
SDL2_ttf/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2_ttf-build/CMakeFiles/SDL2_ttf.dir/build.make _deps/sdl2_ttf-build/CMakeFiles/SDL2_ttf.dir/build
.PHONY : SDL2_ttf/fast

#=============================================================================
# Target rules for targets named SDL2pp

# Build rule for target.
SDL2pp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2pp
.PHONY : SDL2pp

# fast build rule for target.
SDL2pp/fast:
	$(MAKE) $(MAKESILENT) -f _deps/libsdl2pp-build/CMakeFiles/SDL2pp.dir/build.make _deps/libsdl2pp-build/CMakeFiles/SDL2pp.dir/build
.PHONY : SDL2pp/fast

client/controllers/game_controller.o: client/controllers/game_controller.cpp.o
.PHONY : client/controllers/game_controller.o

# target to build an object file
client/controllers/game_controller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/controllers/game_controller.cpp.o
.PHONY : client/controllers/game_controller.cpp.o

client/controllers/game_controller.i: client/controllers/game_controller.cpp.i
.PHONY : client/controllers/game_controller.i

# target to preprocess a source file
client/controllers/game_controller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/controllers/game_controller.cpp.i
.PHONY : client/controllers/game_controller.cpp.i

client/controllers/game_controller.s: client/controllers/game_controller.cpp.s
.PHONY : client/controllers/game_controller.s

# target to generate assembly for a file
client/controllers/game_controller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/controllers/game_controller.cpp.s
.PHONY : client/controllers/game_controller.cpp.s

client/main.o: client/main.cpp.o
.PHONY : client/main.o

# target to build an object file
client/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/main.cpp.o
.PHONY : client/main.cpp.o

client/main.i: client/main.cpp.i
.PHONY : client/main.i

# target to preprocess a source file
client/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/main.cpp.i
.PHONY : client/main.cpp.i

client/main.s: client/main.cpp.s
.PHONY : client/main.s

# target to generate assembly for a file
client/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/main.cpp.s
.PHONY : client/main.cpp.s

client/views/game_view.o: client/views/game_view.cpp.o
.PHONY : client/views/game_view.o

# target to build an object file
client/views/game_view.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/views/game_view.cpp.o
.PHONY : client/views/game_view.cpp.o

client/views/game_view.i: client/views/game_view.cpp.i
.PHONY : client/views/game_view.i

# target to preprocess a source file
client/views/game_view.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/views/game_view.cpp.i
.PHONY : client/views/game_view.cpp.i

client/views/game_view.s: client/views/game_view.cpp.s
.PHONY : client/views/game_view.s

# target to generate assembly for a file
client/views/game_view.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/views/game_view.cpp.s
.PHONY : client/views/game_view.cpp.s

common/game.o: common/game.cpp.o
.PHONY : common/game.o

# target to build an object file
common/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/game.cpp.o
.PHONY : common/game.cpp.o

common/game.i: common/game.cpp.i
.PHONY : common/game.i

# target to preprocess a source file
common/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/game.cpp.i
.PHONY : common/game.cpp.i

common/game.s: common/game.cpp.s
.PHONY : common/game.s

# target to generate assembly for a file
common/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/game.cpp.s
.PHONY : common/game.cpp.s

common/liberror.o: common/liberror.cpp.o
.PHONY : common/liberror.o

# target to build an object file
common/liberror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/liberror.cpp.o
.PHONY : common/liberror.cpp.o

common/liberror.i: common/liberror.cpp.i
.PHONY : common/liberror.i

# target to preprocess a source file
common/liberror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/liberror.cpp.i
.PHONY : common/liberror.cpp.i

common/liberror.s: common/liberror.cpp.s
.PHONY : common/liberror.s

# target to generate assembly for a file
common/liberror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/liberror.cpp.s
.PHONY : common/liberror.cpp.s

common/player.o: common/player.cpp.o
.PHONY : common/player.o

# target to build an object file
common/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/player.cpp.o
.PHONY : common/player.cpp.o

common/player.i: common/player.cpp.i
.PHONY : common/player.i

# target to preprocess a source file
common/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/player.cpp.i
.PHONY : common/player.cpp.i

common/player.s: common/player.cpp.s
.PHONY : common/player.s

# target to generate assembly for a file
common/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/player.cpp.s
.PHONY : common/player.cpp.s

common/protocol.o: common/protocol.cpp.o
.PHONY : common/protocol.o

# target to build an object file
common/protocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/protocol.cpp.o
.PHONY : common/protocol.cpp.o

common/protocol.i: common/protocol.cpp.i
.PHONY : common/protocol.i

# target to preprocess a source file
common/protocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/protocol.cpp.i
.PHONY : common/protocol.cpp.i

common/protocol.s: common/protocol.cpp.s
.PHONY : common/protocol.s

# target to generate assembly for a file
common/protocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/protocol.cpp.s
.PHONY : common/protocol.cpp.s

common/resolver.o: common/resolver.cpp.o
.PHONY : common/resolver.o

# target to build an object file
common/resolver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolver.cpp.o
.PHONY : common/resolver.cpp.o

common/resolver.i: common/resolver.cpp.i
.PHONY : common/resolver.i

# target to preprocess a source file
common/resolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolver.cpp.i
.PHONY : common/resolver.cpp.i

common/resolver.s: common/resolver.cpp.s
.PHONY : common/resolver.s

# target to generate assembly for a file
common/resolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolver.cpp.s
.PHONY : common/resolver.cpp.s

common/resolvererror.o: common/resolvererror.cpp.o
.PHONY : common/resolvererror.o

# target to build an object file
common/resolvererror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolvererror.cpp.o
.PHONY : common/resolvererror.cpp.o

common/resolvererror.i: common/resolvererror.cpp.i
.PHONY : common/resolvererror.i

# target to preprocess a source file
common/resolvererror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolvererror.cpp.i
.PHONY : common/resolvererror.cpp.i

common/resolvererror.s: common/resolvererror.cpp.s
.PHONY : common/resolvererror.s

# target to generate assembly for a file
common/resolvererror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolvererror.cpp.s
.PHONY : common/resolvererror.cpp.s

common/socket.o: common/socket.cpp.o
.PHONY : common/socket.o

# target to build an object file
common/socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/socket.cpp.o
.PHONY : common/socket.cpp.o

common/socket.i: common/socket.cpp.i
.PHONY : common/socket.i

# target to preprocess a source file
common/socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/socket.cpp.i
.PHONY : common/socket.cpp.i

common/socket.s: common/socket.cpp.s
.PHONY : common/socket.s

# target to generate assembly for a file
common/socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/socket.cpp.s
.PHONY : common/socket.cpp.s

common/team.o: common/team.cpp.o
.PHONY : common/team.o

# target to build an object file
common/team.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/team.cpp.o
.PHONY : common/team.cpp.o

common/team.i: common/team.cpp.i
.PHONY : common/team.i

# target to preprocess a source file
common/team.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/team.cpp.i
.PHONY : common/team.cpp.i

common/team.s: common/team.cpp.s
.PHONY : common/team.s

# target to generate assembly for a file
common/team.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/team.cpp.s
.PHONY : common/team.cpp.s

common/weapon.o: common/weapon.cpp.o
.PHONY : common/weapon.o

# target to build an object file
common/weapon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/weapon.cpp.o
.PHONY : common/weapon.cpp.o

common/weapon.i: common/weapon.cpp.i
.PHONY : common/weapon.i

# target to preprocess a source file
common/weapon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/weapon.cpp.i
.PHONY : common/weapon.cpp.i

common/weapon.s: common/weapon.cpp.s
.PHONY : common/weapon.s

# target to generate assembly for a file
common/weapon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/weapon.cpp.s
.PHONY : common/weapon.cpp.s

editor/main.o: editor/main.cpp.o
.PHONY : editor/main.o

# target to build an object file
editor/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_editor.dir/build.make CMakeFiles/taller_editor.dir/editor/main.cpp.o
.PHONY : editor/main.cpp.o

editor/main.i: editor/main.cpp.i
.PHONY : editor/main.i

# target to preprocess a source file
editor/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_editor.dir/build.make CMakeFiles/taller_editor.dir/editor/main.cpp.i
.PHONY : editor/main.cpp.i

editor/main.s: editor/main.cpp.s
.PHONY : editor/main.s

# target to generate assembly for a file
editor/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_editor.dir/build.make CMakeFiles/taller_editor.dir/editor/main.cpp.s
.PHONY : editor/main.cpp.s

server/acceptor.o: server/acceptor.cpp.o
.PHONY : server/acceptor.o

# target to build an object file
server/acceptor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/acceptor.cpp.o
.PHONY : server/acceptor.cpp.o

server/acceptor.i: server/acceptor.cpp.i
.PHONY : server/acceptor.i

# target to preprocess a source file
server/acceptor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/acceptor.cpp.i
.PHONY : server/acceptor.cpp.i

server/acceptor.s: server/acceptor.cpp.s
.PHONY : server/acceptor.s

# target to generate assembly for a file
server/acceptor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/acceptor.cpp.s
.PHONY : server/acceptor.cpp.s

server/admin.o: server/admin.cpp.o
.PHONY : server/admin.o

# target to build an object file
server/admin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/admin.cpp.o
.PHONY : server/admin.cpp.o

server/admin.i: server/admin.cpp.i
.PHONY : server/admin.i

# target to preprocess a source file
server/admin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/admin.cpp.i
.PHONY : server/admin.cpp.i

server/admin.s: server/admin.cpp.s
.PHONY : server/admin.s

# target to generate assembly for a file
server/admin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/admin.cpp.s
.PHONY : server/admin.cpp.s

server/clientHandler.o: server/clientHandler.cpp.o
.PHONY : server/clientHandler.o

# target to build an object file
server/clientHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/clientHandler.cpp.o
.PHONY : server/clientHandler.cpp.o

server/clientHandler.i: server/clientHandler.cpp.i
.PHONY : server/clientHandler.i

# target to preprocess a source file
server/clientHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/clientHandler.cpp.i
.PHONY : server/clientHandler.cpp.i

server/clientHandler.s: server/clientHandler.cpp.s
.PHONY : server/clientHandler.s

# target to generate assembly for a file
server/clientHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/clientHandler.cpp.s
.PHONY : server/clientHandler.cpp.s

server/game_loop.o: server/game_loop.cpp.o
.PHONY : server/game_loop.o

# target to build an object file
server/game_loop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/game_loop.cpp.o
.PHONY : server/game_loop.cpp.o

server/game_loop.i: server/game_loop.cpp.i
.PHONY : server/game_loop.i

# target to preprocess a source file
server/game_loop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/game_loop.cpp.i
.PHONY : server/game_loop.cpp.i

server/game_loop.s: server/game_loop.cpp.s
.PHONY : server/game_loop.s

# target to generate assembly for a file
server/game_loop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/game_loop.cpp.s
.PHONY : server/game_loop.cpp.s

server/lobby.o: server/lobby.cpp.o
.PHONY : server/lobby.o

# target to build an object file
server/lobby.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/lobby.cpp.o
.PHONY : server/lobby.cpp.o

server/lobby.i: server/lobby.cpp.i
.PHONY : server/lobby.i

# target to preprocess a source file
server/lobby.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/lobby.cpp.i
.PHONY : server/lobby.cpp.i

server/lobby.s: server/lobby.cpp.s
.PHONY : server/lobby.s

# target to generate assembly for a file
server/lobby.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/lobby.cpp.s
.PHONY : server/lobby.cpp.s

server/lobbyClientHandler.o: server/lobbyClientHandler.cpp.o
.PHONY : server/lobbyClientHandler.o

# target to build an object file
server/lobbyClientHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/lobbyClientHandler.cpp.o
.PHONY : server/lobbyClientHandler.cpp.o

server/lobbyClientHandler.i: server/lobbyClientHandler.cpp.i
.PHONY : server/lobbyClientHandler.i

# target to preprocess a source file
server/lobbyClientHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/lobbyClientHandler.cpp.i
.PHONY : server/lobbyClientHandler.cpp.i

server/lobbyClientHandler.s: server/lobbyClientHandler.cpp.s
.PHONY : server/lobbyClientHandler.s

# target to generate assembly for a file
server/lobbyClientHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/lobbyClientHandler.cpp.s
.PHONY : server/lobbyClientHandler.cpp.s

server/main.o: server/main.cpp.o
.PHONY : server/main.o

# target to build an object file
server/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/main.cpp.o
.PHONY : server/main.cpp.o

server/main.i: server/main.cpp.i
.PHONY : server/main.i

# target to preprocess a source file
server/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/main.cpp.i
.PHONY : server/main.cpp.i

server/main.s: server/main.cpp.s
.PHONY : server/main.s

# target to generate assembly for a file
server/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/main.cpp.s
.PHONY : server/main.cpp.s

server/server.o: server/server.cpp.o
.PHONY : server/server.o

# target to build an object file
server/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/server.cpp.o
.PHONY : server/server.cpp.o

server/server.i: server/server.cpp.i
.PHONY : server/server.i

# target to preprocess a source file
server/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/server.cpp.i
.PHONY : server/server.cpp.i

server/server.s: server/server.cpp.s
.PHONY : server/server.s

# target to generate assembly for a file
server/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/server.cpp.s
.PHONY : server/server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sdl_headers_copy"
	@echo "... uninstall"
	@echo "... SDL2"
	@echo "... SDL2-static"
	@echo "... SDL2_image"
	@echo "... SDL2_mixer"
	@echo "... SDL2_test"
	@echo "... SDL2_ttf"
	@echo "... SDL2main"
	@echo "... SDL2pp"
	@echo "... taller_client"
	@echo "... taller_common"
	@echo "... taller_editor"
	@echo "... taller_server"
	@echo "... client/controllers/game_controller.o"
	@echo "... client/controllers/game_controller.i"
	@echo "... client/controllers/game_controller.s"
	@echo "... client/main.o"
	@echo "... client/main.i"
	@echo "... client/main.s"
	@echo "... client/views/game_view.o"
	@echo "... client/views/game_view.i"
	@echo "... client/views/game_view.s"
	@echo "... common/game.o"
	@echo "... common/game.i"
	@echo "... common/game.s"
	@echo "... common/liberror.o"
	@echo "... common/liberror.i"
	@echo "... common/liberror.s"
	@echo "... common/player.o"
	@echo "... common/player.i"
	@echo "... common/player.s"
	@echo "... common/protocol.o"
	@echo "... common/protocol.i"
	@echo "... common/protocol.s"
	@echo "... common/resolver.o"
	@echo "... common/resolver.i"
	@echo "... common/resolver.s"
	@echo "... common/resolvererror.o"
	@echo "... common/resolvererror.i"
	@echo "... common/resolvererror.s"
	@echo "... common/socket.o"
	@echo "... common/socket.i"
	@echo "... common/socket.s"
	@echo "... common/team.o"
	@echo "... common/team.i"
	@echo "... common/team.s"
	@echo "... common/weapon.o"
	@echo "... common/weapon.i"
	@echo "... common/weapon.s"
	@echo "... editor/main.o"
	@echo "... editor/main.i"
	@echo "... editor/main.s"
	@echo "... server/acceptor.o"
	@echo "... server/acceptor.i"
	@echo "... server/acceptor.s"
	@echo "... server/admin.o"
	@echo "... server/admin.i"
	@echo "... server/admin.s"
	@echo "... server/clientHandler.o"
	@echo "... server/clientHandler.i"
	@echo "... server/clientHandler.s"
	@echo "... server/game_loop.o"
	@echo "... server/game_loop.i"
	@echo "... server/game_loop.s"
	@echo "... server/lobby.o"
	@echo "... server/lobby.i"
	@echo "... server/lobby.s"
	@echo "... server/lobbyClientHandler.o"
	@echo "... server/lobbyClientHandler.i"
	@echo "... server/lobbyClientHandler.s"
	@echo "... server/main.o"
	@echo "... server/main.i"
	@echo "... server/main.s"
	@echo "... server/server.o"
	@echo "... server/server.i"
	@echo "... server/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

