#ifndef GAMECONSTANTS_H
#define GAMECONSTANTS_H

enum class Role { TERRORIST, COUNTER_TERRORIST };

#define SPEED 5.0f
#define MAX_PLAYERS_PER_TEAM 5
#define PLAYER_WIDTH 1.7f
#define PLAYER_HEIGHT 1.7f

#endif
