
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/marina/taller/tpg/Counter2D-2025c1-grupo9/cmake-3.27.9-linux-x86_64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.8.0-59-generic - x86_64
...
